// frontend/pages/auth/github-callback.vue
<script setup lang="ts">
	import { Loader2 } from "lucide-vue-next";
	import { useAuthStore } from "~/stores/auth";
import type { StudentUser } from "~/types/user";

	const router = useRouter();
	const route = useRoute();
	const authStore = useAuthStore();
	const { completeGithubLogin } = useApiClient();

	const status = ref<"loading" | "error" | "success">("loading");
	const message = ref("");

	onMounted(async () => {
		try {
			const code = route.query.code as string | undefined;
			const state = route.query.state as string | undefined;
			const error = route.query.error as string | undefined;
			console.log("GitHub callback received with query params:", route.query);

			// Check for OAuth error from GitHub
			if (error) {
				status.value = "error";
				message.value = `GitHub authorization failed: ${error}`;
				return;
			}

			// Validate code is present
			if (!code) {
				status.value = "error";
				message.value = "No authorization code received from GitHub. Please try again.";
				return;
			}

			// CSRF: validate state parameter
			const savedState = sessionStorage.getItem("github_oauth_state");
			if (!state || state !== savedState) {
				status.value = "error";
				message.value = "Invalid state parameter. This may be a CSRF attack. Please try again.";
				return;
			}

			// Retrieve stored studentId
			const studentId = sessionStorage.getItem("github_student_id");
			if (!studentId) {
				status.value = "error";
				message.value = "Student ID not found. Please go back and enter your Student ID.";
				return;
			}

			// Clean up session storage
			sessionStorage.removeItem("github_oauth_state");
			sessionStorage.removeItem("github_student_id");

			console.log("Received GitHub callback with code:", code, "and studentId:", studentId);

			// Send code + studentId to backend; backend exchanges code for token
			const response = await completeGithubLogin(code, studentId);

			// Store auth state via Pinia store
			authStore.login(response.token, {
				userType: 'Student',
				id: response.userInfo.id,
				studentId,
				githubUsername: response.userInfo.githubUsername,
				role: "Student"
			} as StudentUser);

			status.value = "success";
			message.value = "Authentication successful. Redirecting...";

			setTimeout(() => {
				router.push("/student/dashboard");
			}, 1500);
		} catch (err: unknown) {
			status.value = "error";
			const errorMsg =
				err && typeof err === "object" && "message" in err
					? String(err.message)
					: "An unexpected error occurred. Please try again.";
			message.value = errorMsg;
		}
	});
</script>

<template>
  <main class="flex min-h-screen items-center justify-center bg-gradient-to-br from-slate-50 via-white to-slate-100 px-4 py-10 dark:from-slate-950 dark:via-slate-900 dark:to-slate-950">
    <!-- Background gradient for dark mode -->
    <div
      class="pointer-events-none absolute inset-0 hidden dark:block"
      aria-hidden="true"
      :style="{
        background: 'radial-gradient(48rem 28rem at 50% 34%, rgba(59,130,246,0.14), rgba(15,23,42,0) 70%)',
        filter: 'blur(14px)',
      }"
    ></div>

    <section class="relative z-10 w-full max-w-md space-y-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-lg dark:border-slate-700 dark:bg-slate-900 dark:shadow-xl md:p-8">
      <!-- Loading State -->
      <div v-if="status === 'loading'" class="flex flex-col items-center justify-center gap-4 text-center">
        <div class="inline-flex h-12 w-12 items-center justify-center rounded-full bg-blue-100 dark:bg-blue-950/50">
          <Loader2 class="h-6 w-6 animate-spin text-blue-600 dark:text-blue-400" />
        </div>
        <h1 class="text-2xl font-semibold text-slate-900 dark:text-white">
          Authenticating...
        </h1>
        <p class="text-slate-600 dark:text-slate-400">
          Please wait while we complete your GitHub login
        </p>
      </div>

      <!-- Success State -->
      <div v-else-if="status === 'success'" class="flex flex-col items-center justify-center gap-4 text-center">
        <div class="inline-flex h-12 w-12 items-center justify-center rounded-full bg-green-100 dark:bg-green-950/50">
          <svg class="h-6 w-6 text-green-600 dark:text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" :stroke-width="2" d="M5 13l4 4L19 7" />
          </svg>
        </div>
        <h1 class="text-2xl font-semibold text-slate-900 dark:text-white">
          {{ message }}
        </h1>
        <p class="text-slate-600 dark:text-slate-400">
          You will be redirected to your dashboard shortly.
        </p>
      </div>

      <!-- Error State -->
      <div v-else-if="status === 'error'" class="flex flex-col items-center justify-center gap-4 text-center">
        <div class="inline-flex h-12 w-12 items-center justify-center rounded-full bg-red-100 dark:bg-red-950/50">
          <svg class="h-6 w-6 text-red-600 dark:text-red-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" :stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </div>
        <h1 class="text-2xl font-semibold text-red-900 dark:text-red-100">
          Authentication Failed
        </h1>
        <p class="text-red-700 dark:text-red-300">{{ message }}</p>
        <div class="pt-2">
          <NuxtLink
            to="/auth/login?tab=students"
            class="inline-flex items-center justify-center rounded-lg bg-red-600 px-6 py-2 text-sm font-medium text-white transition hover:bg-red-700 dark:bg-red-700 dark:hover:bg-red-600"
          >
            Back to Login
          </NuxtLink>
        </div>
      </div>
    </section>
  </main>
</template>

// frontend/app/(auth)/github-callback/page.tsx
"use client";

import { Suspense, useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { Loader2 } from "lucide-react";

/**
 * GitHub OAuth Callback Handler
 * This page is called by GitHub OAuth redirect after user authorizes
 * Handles token reception and session setup
 *
 * URL Pattern: http://localhost:3000/auth/github/callback?token=JWT&state=STATE
 * Backend should redirect here after successful GitHub authentication
 */
function GitHubCallbackContent() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const [status, setStatus] = useState<"loading" | "error" | "success">(
    "loading"
  );
  const [message, setMessage] = useState("");

  useEffect(() => {
    const handleCallback = async () => {
      try {
        // Extract JWT token from URL query parameters
        const token = searchParams.get("token");
        const state = searchParams.get("state");
        const error = searchParams.get("error");

        // Check for OAuth error
        if (error) {
          setStatus("error");
          setMessage(`GitHub authorization failed: ${error}`);
          return;
        }

        // Check if token is present
        if (!token) {
          setStatus("error");
          setMessage("No authentication token received. Please try again.");
          return;
        }

        // Store JWT token in localStorage
        localStorage.setItem("authToken", token);

        // Parse and store user info if available
        // You may want to decode the JWT and extract user role
        try {
          // Simple JWT decode (not secure, should validate on backend)
          const parts = token.split(".");
          if (parts.length === 3) {
            const payload = JSON.parse(atob(parts[1]));
            localStorage.setItem("userInfo", JSON.stringify(payload));
          }
        } catch (e) {
          console.warn("Could not decode JWT payload");
        }

        // Success - redirect to student dashboard
        setStatus("success");
        setMessage("Authentication successful. Redirecting...");

        // Redirect after brief delay
        setTimeout(() => {
          router.push("/student/dashboard");
        }, 1500);
      } catch (err) {
        setStatus("error");
        setMessage("An unexpected error occurred. Please try again.");
      }
    };

    handleCallback();
  }, [searchParams, router]);

  return (
    <main className="flex min-h-screen items-center justify-center bg-gradient-to-br from-slate-50 via-white to-slate-100 px-4 py-10 dark:from-slate-950 dark:via-slate-900 dark:to-slate-950">
      {/* Background gradient for dark mode */}
      <div
        className="pointer-events-none absolute inset-0 hidden dark:block"
        aria-hidden="true"
        style={{
          background:
            "radial-gradient(48rem 28rem at 50% 34%, rgba(59,130,246,0.14), rgba(15,23,42,0) 70%)",
          filter: "blur(14px)",
        }}
      />

      {/* Content */}
      <section className="relative z-10 w-full max-w-md space-y-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-lg dark:border-slate-700 dark:bg-slate-900 dark:shadow-xl md:p-8">
        {/* Loading State */}
        {status === "loading" && (
          <div className="flex flex-col items-center justify-center gap-4 text-center">
            <div className="inline-flex h-12 w-12 items-center justify-center rounded-full bg-blue-100 dark:bg-blue-950/50">
              <Loader2 className="h-6 w-6 animate-spin text-blue-600 dark:text-blue-400" />
            </div>
            <h1 className="text-2xl font-semibold text-slate-900 dark:text-white">
              Authenticating...
            </h1>
            <p className="text-slate-600 dark:text-slate-400">
              Please wait while we complete your GitHub login
            </p>
          </div>
        )}

        {/* Success State */}
        {status === "success" && (
          <div className="flex flex-col items-center justify-center gap-4 text-center">
            <div className="inline-flex h-12 w-12 items-center justify-center rounded-full bg-green-100 dark:bg-green-950/50">
              <svg
                className="h-6 w-6 text-green-600 dark:text-green-400"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M5 13l4 4L19 7"
                />
              </svg>
            </div>
            <h1 className="text-2xl font-semibold text-slate-900 dark:text-white">
              {message}
            </h1>
            <p className="text-slate-600 dark:text-slate-400">
              You will be redirected to your dashboard shortly.
            </p>
          </div>
        )}

        {/* Error State */}
        {status === "error" && (
          <div className="flex flex-col items-center justify-center gap-4 text-center">
            <div className="inline-flex h-12 w-12 items-center justify-center rounded-full bg-red-100 dark:bg-red-950/50">
              <svg
                className="h-6 w-6 text-red-600 dark:text-red-400"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </div>
            <h1 className="text-2xl font-semibold text-red-900 dark:text-red-100">
              Authentication Failed
            </h1>
            <p className="text-red-700 dark:text-red-300">{message}</p>

            <div className="pt-2">
              <a
                href="/login?tab=students"
                className="inline-flex items-center justify-center rounded-lg bg-red-600 px-6 py-2 text-sm font-medium text-white transition hover:bg-red-700 dark:bg-red-700 dark:hover:bg-red-600"
              >
                Back to Login
              </a>
            </div>
          </div>
        )}
      </section>
    </main>
  );
}

export default function GitHubCallbackPage() {
  return (
    <Suspense
      fallback={
        <main className="flex min-h-screen items-center justify-center bg-gradient-to-br from-slate-50 via-white to-slate-100 px-4 py-10 dark:from-slate-950 dark:via-slate-900 dark:to-slate-950">
          <section className="relative z-10 w-full max-w-md space-y-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-lg dark:border-slate-700 dark:bg-slate-900 dark:shadow-xl md:p-8">
            <div className="flex flex-col items-center justify-center gap-4 text-center">
              <div className="inline-flex h-12 w-12 items-center justify-center rounded-full bg-blue-100 dark:bg-blue-950/50">
                <Loader2 className="h-6 w-6 animate-spin text-blue-600 dark:text-blue-400" />
              </div>
              <h1 className="text-2xl font-semibold text-slate-900 dark:text-white">
                Loading...
              </h1>
            </div>
          </section>
        </main>
      }
    >
      <GitHubCallbackContent />
    </Suspense>
  );
}
